### ISSUE TITLE
Array capacities are not validated when loading exported databases

### ISSUE THREAD

**Issue by LeoCodes21** [NFSTools/YAMLDatabase#6]
The following data:
```yml
    transmission:
      Capacity: 2
      Data:
      - ClassKey: transmission
        CollectionKey: brera
      - ClassKey: transmission
        CollectionKey: brera_h
      - ClassKey: transmission
        CollectionKey: brera_a
      - ClassKey: transmission
        CollectionKey: brera_t
```

is invalid because there are 4 elements in the array, but the array has a specified capacity of 2. The generated files work in-game, but cannot be loaded by VaultLib due to an internal error in the array loader.
